### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by CloudburstSys** [Manechat/izzy-moonbot#159] opened 2022-11-30 09:09 UTC
It's become obvious that Izzy will require a Wildcard helper in order to implement support for wildcards in both witties (#61) and filter (#154) in order to avoid code duplication, however I think it's currently up in the air on what specific characters should do stuff. We should discuss this and set in stone what special characters do what.

The goal is to not be as complex as Regexp, while also still being complex enough to be useful.

For now, the characters I know should do things are listed here:

- `*` Wildcard, any character can be here and still match.
- `**` Extreme wildcard, any number of characters can be here up to the literal characters after this and still match.
- `\` Escape, the character after this will be interpreted literally instead of any special function.
- `|` Or, allows for matching either the left side or the right side. Can be chained.

If there are any more, please post them here

**Comment by Ixrec** [comment] 2023-11-14 21:47
I'm going to close this as a duplicate of #154, since when we got around to properly studying Sweetie's witties, I came to the surprising conclusion that Izzy's witties don't need any pattern matching syntax at all: https://github.com/Manechat/izzy-moonbot/issues/61#issuecomment-1681341702 and three months later we have yet to see any feedback that this was a bad call.

**Closed by Ixrec** 2023-11-14 21:47 UTC
Labels: needs discussion, size: medium
